### ISSUE TITLE
DOCs: Broken link for "Change Streams Kafka producer lab" in README.md file

### ISSUE THREAD

**Issue by chethan477** [rlondner/mongodb-3.6-workshop#3]
Hi,
the link for "Change Streams Kafka producer lab" in README.md file is pointing to https://github.com/rlondner/mongodb-3.6-workshop/tree/master/labs/kafka
the actual link is https://github.com/rlondner/mongodb-3.6-workshop/tree/master/labs/change-streams/kafka

**Comment by rlondner** [comment]
Thank you for the note! I've fixed the link now.
